# Hides player join/leave messages in public chat
hideJoinLeaveMessages: false

# Duration in seconds to wait for more players to join
wait-duration: 15
# Teleport players somewhere while waiting for the game to start
# Keep in mind that these coordinates cannot be zero! Use something like 0.5 instead
enable-wait-area: false
wait-area:
  x:
  y:
  z:
  world:

# Place where everyone is teleported to after a game ends REQUIRED
# Keep in mind that these coordinates cannot be zero! Use something like 0.5 instead
lobby-spawn:
  x: 0.5
  y: 100
  z: 0.5
  world: world

# Place that the winner is teleported after a game ends
# Keep in mind that these coordinates cannot be zero! Use something like 0.5 instead
enable-winner-lobby-spawn: false
winner-lobby-spawn:
  x: 
  y: 
  z:
  world:

# Add/remove as you wish
# Keep in mind that these coordinates cannot be zero! Use something like 0.5 instead
arenas:
  'test':
    x: 100
    y: 100
    z: 100
    world: world