# Hides join/leave messages in public chat
# Default is true
hideJoinLeaveMessages: true

# Customize the message that displays when the player does not have permission to execute a command from this plugin
permissionMessage: You do not have permission to perform this command!

# Customize the game mode of Tumble
# Acceptable options include: shovels, snowballs, mixed
# Default is mixed
gameMode: mixed

# Customize the place that the winner is teleported after a game ends
# This is an optional value
# Default is nothing
winnerTeleport:
  # These coordinates cannot be zero! The teleport will fail if any of them are.
  # Use something like 0.5 instead.
  x:
  y:
  z:

# This tells the plugin which worlds it should use as the lobby/game worlds
# Do NOT change unless you know what you're doing!!
# Will be blank by default
lobbyWorld:
# Game world
gameWorld: