# Hides player join and leave messages in public chat during games
hide-join-leave-messages: false

# Hides player death messages in public chat during games
hide-death-messages: false

# Duration (in seconds) to wait for more players to join a game before starting
# Set to 0 to disable
wait-duration: 15
