main: com.MylesAndMore.Tumble.Main
name: Tumble
version: 1.0.4
description: 'A Minecraft: Java Edition plugin recreating the Tumble minigame from Minecraft Legacy Console Edition.'
api-version: 1.16
load: POSTWORLD
author: MylesAndMore
website: https://github.com/MylesAndMore/Tumble
softdepend: [Multiverse-Core]
commands:
  tumble-join:
    description: Joins a Tumble match.
    usage: '§cUsage: /tumble-join <arenaName> [gameType]'
    permission: tumble.join
  tumble-leave:
    description: Quits a Tumble match.
    usage: '§cUsage: /tumble-leave'
    permission: tumble.leave
  tumble-forcestart:
    description: Force starts a Tumble match.
    usage: '§cUsage: /tumble-forcestart [arenaName]'
    permission: tumble.forcestart
  tumble-forcestop:
    description: Force stops a Tumble match.
    usage: '§cUsage: /tumble-forcestop [arenaName]'
    permission: tumble.forcestop
  tumble-config:
    description: Modify arenas and worlds.
    usage: '§cUsage: /tumble-config <add|set|disable|delete> <data>'
    permission: tumble.config
  tumble-reload:
    description: Reloads the plugin's config.
    usage: '§cUsage: /tumble-reload'
    permission: tumble.reload
permissions:
  tumble.join:
    description: Allows you to join a Tumble match.
    default: true
  tumble.leave:
    description: Allows you to leave a Tumble match.
    default: true
  tumble.forcestart:
    description: Allows you to force start a Tumble match.
    default: op
  tumble.forcestop:
    description: Allows you to force stop a Tumble match.
    default: op
  tumble.config:
    description: Allows you to get a notification if Tumble is out of date.
    default: op
  tumble.reload:
    description: Allows you to reload the plugin's config.
    default: op

