main: com.MylesAndMore.Tumble.Main
name: Tumble
version: 1.0.4
description: 'A Minecraft: Java Edition plugin recreating the Tumble minigame from Minecraft Legacy Console Edition.'
api-version: 1.16
load: POSTWORLD
author: MylesAndMore
website: https://github.com/MylesAndMore/Tumble
softdepend: [Multiverse-Core]

commands:
  tumble:
    description: Base command for Rumble
    usage: "/tmbl <subCommand> ..."
    aliases: tmbl

permissions:
  tumble.join:
    description: Allows you to join a Tumble match.
    default: true
  tumble.leave:
    description: Allows you to leave a Tumble match.
    default: true
  tumble.forceStart:
    default: op
  tumble.forceStop:
    default: op
  tumble.reload:
    default: op
  tumble.create:
    default: op
  tumble.remove:
    default: op
  tumble.setGameSpawn:
    default: op
  tumble.setKillYLevel:
    default: op
  tumble.setLobby:
    default: op
  tumble.setWaitArea:
    default: op
  tumble.setWinnerLobby:
    default: op

