main: com.MylesAndMore.tumble.Main
name: tumble
version: 1.0.0
description: 'A Minecraft: Java Edition plugin recreating the Tumble minigame from Minecraft Legacy Console Edition.'
api-version: 1.19
load: STARTUP
author: MylesAndMore
website: https://github.com/MylesAndMore/tumble
depend:
  - Multiverse-Core
commands:
  reload:
    description: Reloads the plugin's config.
    usage: '§cUsage: /tumble:reload'
    permission: reload
  link:
    description: Links a world on the server as a lobby/game world.
    usage: '§cUsage: /tumble:link <world> (lobby|game)'
    permission: link
    aliases: [linkworld, link-world]
  start:
    description: Force starts a Tumble match with an optional game type.
    usage: '§cUsage: /tumble:start [gameType]'
    permission: start
  winlocation:
    description: Links the location to teleport the winning player of a game.
    usage: '§cUsage: /tumble:winlocation [x] [y] [z]'
    permission: winlocation
    aliases: [win-location, winloc, win-loc]
  autostart:
    description: Configures the auto start functions of Tumble.
    usage: '§cUsage: /tumble:autostart <playerAmount> [enable|disable]'
    permission: autostart
    aliases: [auto-start]
permissions:
  reload:
    description: Allows you to reload the plugin's config.
    default: op
  link:
    description: Allows you to link a world on the server as a lobby/game world.
    default: op
  start:
    description: Allows you to start a Tumble match.
    default: op
  winlocation:
    description: Allows you to link a win location.
    default: op
  autostart:
    description: Allows you to set the autostart details of Tumble.
    default: op
