main: com.MylesAndMore.tumble.Main
name: tumble
version: 0.0.1-SNAPSHOT
description: 'A Minecraft: Java Edition plugin recreating the Tumble minigame from Minecraft: Xbox 360 Edition.'
api-version: 1.19
load: STARTUP
author: MylesAndMore
website: https://github.com/MylesAndMore/tumble
depend:
  - Multiverse-Core
commands:
  reload:
    description: Reloads the plugin's config.
    usage: /tumble:reload
    permission: reload
  setworld:
    description: Sets a world on the server as a lobby/game world.
    usage: /tumble:setworld <world> lobby|game
    permission: setworld
    aliases: [set-world]
  start:
    description: Force starts a Tumble match.
    usage: /tumble:startgame
    permission: startgame
permissions:
  reload:
    description: Allows you to reload the plugin's config.
    default: op
  setworld:
    description: Allows you to set a world on the server as a lobby/game world.
    default: op
  start:
    description: Allows you to start a Tumble match.
    default: op
