main: com.MylesAndMore.tumble.Main
name: tumble
version: 0.0.1-SNAPSHOT
description: 'A Minecraft: Java Edition plugin recreating the Tumble minigame from Minecraft: Xbox 360 Edition.'
api-version: 1.19
load: STARTUP
author: MylesAndMore
website: https://github.com/MylesAndMore/tumble
depend:
  - Multiverse-Core
commands:
  reload:
    description: Reloads the plugin's config.
    usage: '§cUsage: /tumble:reload'
    permission: reload
  link:
    description: Links a world on the server as a lobby/game world.
    usage: '§cUsage: /tumble:link <world> lobby|game'
    permission: link
    aliases: [linkworld, link-world]
  start:
    description: Force starts a Tumble match.
    usage: '§cUsage: /tumble:start'
    permission: start
permissions:
  reload:
    description: Allows you to reload the plugin's config.
    default: op
  link:
    description: Allows you to link a world on the server as a lobby/game world.
    default: op
  start:
    description: Allows you to start a Tumble match.
    default: op
